### PR TITLE
lint using resharper

### PR DESCRIPTION
**Pull request by harryob**
implements linting using rider's annotation tool, resharper. these lints aren't annotated using standard github pattern as there is a Ton of them, and resharper outputs them in SARIF. the best fitting tool for this seems to be the codeql security analysis tool, which is odd for a linter, but i think it still provides handy annotation

oh no! new bad code!! (only shows new inspections on the pr, not existing ones)
CleanShot 2024-05-22 at 23 21 59@2x

new commit addresses the issue, the issue is flagged as fixed and minimised
CleanShot 2024-05-22 at 23 27 08@2x

### CODE REVIEW

**Comment by wixoaGit** [comment]
This gives a ton of errors for our XAML UI. Is there something that can be done about that?
image

**Comment by harryob** [comment]
> This gives a ton of errors for our XAML UI (~6 pages). Is there something that can be done about that? image

that's odd, i never got anything reporting as an error on my fork. i'll add an exclusion for reporting anything on .xaml pages, given it seems to be misreporting for them anyway

**Comment by wixoaGit** [comment]
Turns out to also be giving lots of errors for things defined in RobustToolbox. This is probably due to the RT projects being excluded.
image

**Comment by harryob** [comment]
> Turns out to also be giving lots of errors for things defined in RobustToolbox. This is probably due to the RT projects being excluded. image

added a flag to skip the build to cut linting times, but this ended up also skipping the restore that happened - manually forcing it the restore seems to ensure the analysis works correctly

**Review by wixoaGit — APPROVED** [review]

**Pull request merged**
