### PR TITLE
Parser lookahead fix

### PR DESCRIPTION
**Pull request by mumencoder**

### CODE REVIEW

**Comment by willox** [comment]
I think ReuseToken requires the following:

```csharp
    if (_lookahead.Count > 0) {
        _lookahead.Peek().Pop();
    }
```

**Comment by willox** [comment]
I also think that AcceptPosition should be:
```csharp
    _lookahead.Pop();
```

**Comment by mumencoder** [comment]
> I think ReuseToken requires the following:
> 
> ```cs
>     if (_lookahead.Count > 0) {
>         _lookahead.Peek().Pop();
>     }
> ```

This does mostly fix the combination of ReuseToken and the lookahead function calls. Testing showed that it is still important for an Advance to be the next state change after calls to both SavePosition and RestorePosition. Also an Accept cannot directly follow a Reuse.

**Comment by wixoaGit** [comment]
Nothing uses these methods and honestly I'd rather get rid of them

**Pull request closed without merging**
