### PR TITLE
Fix whitespace before `#include`

### LINKED ISSUE #1050: Indentation before #include causes undefined var error
## Description

OpenDream fails to parse first object definition in the file, when file's include line begins with indentation.

## Steps to reproduce

Add folowing line starting with indentation to TestGame .dme file:

```
    #include "exodus_announcements.dm"
```

Example "exodus_announcements.dm" file content:

```
/obj/TestObj
	a = "The Emergency Shuttle has docked with the station. You have approximately %ETD% to board the Emergency Shuttle."
```

OpenDream compiles with error:

```
Error OD0405 at exodus_announcements.dm:2:4: Cannot override undefined var "a"
```

At the same time, BYOND compiles it without any issues.

## Initial research

I've taken a look to this problem in the debugger and found that problem is in DMLexer. DMObjectBuilder tries to process `/obj/TestObj/a` override statement, and encounters wrong statement's ObjectPath:

image

ObjectPath should be `/obj/TestObj` instead of `/datum/map` which is simply previous processed block's ObjectPath.

## Workaround

Removing indentation before #include file's line solves the problem.

### PR DESCRIPTION
**Pull request by ike709**
Closes #1050 

I did test it locally but I already had the file open on github so it was easier to webedit than push a commit.

### CODE REVIEW

**Comment by out-of-phaze** [comment]
Confirmed to fix the issue we had with this on Nebula.

**Comment by ike709** [comment]
Now that I think about it, I need to test if this causes error line numbers to be off by one.

**Comment by out-of-phaze** [comment]
> Now that I think about it, I need to test if this causes error line numbers to be off by one.

Debugger line numbers were off by one but I don't know if that's related or if it occurred before I locally merged this PR.

**Comment by ike709** [comment]
This isn't the ideal fix and I cba to revisit this right now.

**Pull request closed without merging**
